// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
#define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
#import <Protobuf/GPBProtocolBuffers.h>
#else
#import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Message_MessageType

typedef GPB_ENUM(Message_MessageType) {
    /**
     * Value used if any message's field encounters a value that is not defined
     * by this enum. The message will also have C functions to get/set the rawValue
     * of the field.
     **/
    Message_MessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
    Message_MessageType_Text = 0,
    Message_MessageType_Image = 1,
    Message_MessageType_Audio = 2,
    Message_MessageType_Connect = 3,
    Message_MessageType_Receipt = 4,
};

GPBEnumDescriptor *Message_MessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Message_MessageType_IsValidValue(int32_t value);

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
    Message_FieldNumber_Version = 1,
    Message_FieldNumber_MessageId = 2,
    Message_FieldNumber_Time = 3,
    Message_FieldNumber_Content = 4,
    Message_FieldNumber_ImageURL = 5,
    Message_FieldNumber_FromUser = 6,
    Message_FieldNumber_ToUser = 7,
    Message_FieldNumber_Type = 8,
    Message_FieldNumber_ImageScale = 9,
};

@interface Message : GPBMessage

@property(nonatomic, readwrite) float version;

@property(nonatomic, readwrite) uint64_t messageId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imageURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toUser;

@property(nonatomic, readwrite) Message_MessageType type;

@property(nonatomic, readwrite) float imageScale;

@end

/**
 * Fetches the raw value of a @c Message's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Message_Type_RawValue(Message *message);
/**
 * Sets the raw value of an @c Message's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMessage_Type_RawValue(Message *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
